update actions config and core
devcontainers/action pull request #100
Opened 2022-11-08 12:38 UTC by devenes

🚨 Node 12 has an end of life on April 30, 2022.

The GitHub Actions workflow gives the following warning while running the action:

> Node.js 12 actions are deprecated. For more information see: github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12.

This PR updates the default runtime to [node16](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/), rather then node12. And resolves this issue: Node.js 12 actions are deprecated #99.

You can see more here: https://github.com/actions/setup-node/compare/v2.5.1...v3.0.0

This is supported on all Actions Runners v2.285.0 or later.

Signed-off-by: Enes <ahmedenesturan@gmail.com>

2022-12-23 17:44 UTC, rfay commented
Time to get this sorted out.

2022-12-27 16:47 UTC, samruddhikhandale requested changes
Thanks for the PR. Left some comments.

2022-12-27 16:47 UTC, samruddhikhandale commented on .github/workflows/publish.yml
> +        uses: actions/checkout@v3.1.0
```suggestion
        uses: actions/checkout@v3
```

Can we pin to the major version? thanks!

2022-12-27 16:47 UTC, samruddhikhandale commented on .github/workflows/publish.yml
> +        uses: actions/setup-node@v3.5.1
Same here!

```suggestion
        uses: actions/setup-node@v3
```

2022-12-27 21:48 UTC, devenes commented
Thanks @samruddhikhandale for your review! Waiting for your feedback.

2022-12-27 21:49 UTC, devenes commented on .github/workflows/publish.yml
> +        uses: actions/checkout@v3.1.0
Many thanks for the great advice!

2022-12-27 22:03 UTC, samruddhikhandale approved these changes
Awesome, Looks great. Thanks!

2022-12-27 22:03 UTC, merged